### ISSUE TITLE
Can't get it to work with any URL

### ISSUE THREAD

**Issue by impressivewebs** [IntToDouble/winded#4]
Doesn't seem to work for me using Brave Browser or Firefox. Every page URL says the source inside the frame can't be loaded. Is there maybe a CORS issue or something? Because the only URL that works is the URL pointing to itself.

**Comment by tycrimm** [comment]
Several pages load when I test Firefox. Mind looking at the console to see if there are any errors?

**Comment by impressivewebs** [comment]
Yeah, it must have been a temporary issue on my system. It seems to be working now just fine. Thanks!
